AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'data/**/*'
    - '.git/**/*'
  SuggestExtensions: false
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Max: 150
# Metrics/LineLength:
#   Max: 100
Style/WordArray:
  Enabled: false
# Style/SymbolProc:
#   Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
